[package]
name = "netmon"
version = "0.1.0"
build = "build.rs"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
rand = "0.9.2"
rumqttc = "0.25.0"
slint = "1.12.1"

[build-dependencies]
slint-build = "1.12.1"
